export const monographsSeed: Monograph[] = [
  {
    Id: 1,
    Name: "Abey",
    genus: "Jacaranda",
    subsp: "",
    f: "",
    species: "coerulea",
    authors: "(L.) Griseb.",
    family: "Bignoniáceas",
    var: "",
    subfamily: "",
    Sy: ["Bignonia coerulea L.", "Jacaranda bahamensis R. Br"],
    Vul: ["Abey macho (Cuba)", "boxwood (EU)"],
    Hab: "Árbol pequeño, se encuentra en las costas, en los terrenos calcáreos pedregosos y en montes bajos, de todas las provincias; pero solo es algo abundante en Camagüey.",
    Des: "Árbol que alcanza una altura máxima de unos 12 m, con el follaje lampiño...",
    Cmp: "",
    Use: "Las hojas y las ramas.",
    Pro: "",
    App: "En Camagüey y en Oriente usan esta planta para baños antisépticos...",
    Cul: "",
    Bib: [
      "Pérez Arbelaez, Enrique: Plantas medicinales y venenosas de Colombia, pp. 257-258, 1937.",
    ],
  },
  {
    Id: 2,
    Name: "Guayaba",
    genus: "Psidium",
    subsp: "",
    f: "",
    species: "guajava",
    authors: "L.",
    family: "Myrtaceae",
    var: "",
    subfamily: "",
    Sy: ["Guayava vulgaris A. Rich."],
    Vul: ["Guayaba (Cuba)", "Guayabo (MX)"],
    Hab: "Árbol o arbusto que crece en terrenos cálidos y húmedos.",
    Des: "Árbol de follaje perenne, de unos 6-8 m de altura, hojas opuestas, flores blancas...",
    Cmp: "Rica en vitamina C, pectina y antioxidantes.",
    Use: "Fruto, hojas y corteza.",
    Pro: "Antidiarreico, antioxidante.",
    App: "Se utiliza para tratar infecciones digestivas y como astringente.",
    Cul: "Se cultiva en zonas tropicales y subtropicales.",
    Bib: ["Roig y Mesa, Tomás: Plantas Medicinales, 1927."],
  },
  {
    Id: 3,
    Name: "Aloe Vera",
    genus: "Aloe",
    subsp: "",
    f: "",
    species: "vera",
    authors: "(L.) Burm.f.",
    family: "Asphodelaceae",
    var: "",
    subfamily: "",
    Sy: ["Aloe barbadensis Mill."],
    Vul: ["Sábila (Cuba)", "Aloe Vera (Estados Unidos)"],
    Hab: "Planta suculenta que crece en climas cálidos y secos.",
    Des: "Planta perenne con hojas carnosas y espinosas, de color verde...",
    Cmp: "Contiene vitaminas, minerales, enzimas y aminoácidos.",
    Use: "Gel de las hojas.",
    Pro: "Cicatrizante, antiinflamatorio, hidratante.",
    App: "Se utiliza para tratar quemaduras, heridas y problemas de la piel.",
    Cul: "Se cultiva en regiones cálidas y secas.",
    Bib: [
      "Grindlay, D. and Reynolds, T.: The Aloe vera phenomenon: A review of the properties and modern uses of the leaf parenchyma gel, Journal of Ethnopharmacology, 1986.",
    ],
  },
  {
    Id: 4,
    Name: "Manzanilla",
    genus: "Matricaria",
    subsp: "",
    f: "",
    species: "chamomilla",
    authors: "L.",
    family: "Asteraceae",
    var: "",
    subfamily: "",
    Sy: ["Chamomilla recutita (L.) Rauschert"],
    Vul: ["Manzanilla (Cuba)", "Camomila (España)"],
    Hab: "Hierba anual que crece en campos y bordes de caminos.",
    Des: "Planta de unos 20-50 cm de altura, con flores blancas y amarillas...",
    Cmp: "Contiene aceites esenciales, flavonoides y cumarinas.",
    Use: "Flores.",
    Pro: "Antiinflamatorio, digestivo, sedante.",
    App: "Se utiliza para tratar problemas digestivos y como calmante.",
    Cul: "Se cultiva en climas templados.",
    Bib: ["Blumenthal, M.: The Complete German Commission E Monographs, 1998."],
  },
  {
    Id: 5,
    Name: "Lavanda",
    genus: "Lavandula",
    subsp: "",
    f: "",
    species: "angustifolia",
    authors: "Mill.",
    family: "Lamiaceae",
    var: "",
    subfamily: "",
    Sy: ["Lavandula officinalis Chaix"],
    Vul: ["Lavanda (Cuba)", "Lavande (Francia)"],
    Hab: "Arbusto perenne que crece en zonas soleadas y secas.",
    Des: "Planta de unos 30-60 cm de altura, con flores violetas...",
    Cmp: "Contiene aceites esenciales, taninos y cumarinas.",
    Use: "Flores y aceite esencial.",
    Pro: "Relajante, antiséptico, antiinflamatorio.",
    App: "Se utiliza para tratar ansiedad, insomnio y heridas.",
    Cul: "Se cultiva en climas mediterráneos.",
    Bib: ["Wichtl, M.: Herbal Drugs and Phytopharmaceuticals, 2004."],
  },
  {
    Id: 6,
    Name: "Menta",
    genus: "Mentha",
    subsp: "",
    f: "",
    species: "piperita",
    authors: "L.",
    family: "Lamiaceae",
    var: "",
    subfamily: "",
    Sy: ["Mentha balsamea Willd."],
    Vul: ["Menta (Cuba)", "Peppermint (Inglaterra)"],
    Hab: "Hierba perenne que crece en zonas húmedas.",
    Des: "Planta de unos 30-90 cm de altura, con hojas verdes y flores lilas...",
    Cmp: "Contiene mentol, flavonoides y ácidos fenólicos.",
    Use: "Hojas y aceite esencial.",
    Pro: "Digestivo, antiespasmódico, carminativo.",
    App: "Se utiliza para tratar problemas digestivos y respiratorios.",
    Cul: "Se cultiva en climas templados.",
    Bib: ["Grieve, M.: A Modern Herbal, 1931."],
  },
];
