using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace DataAccess.Migrations
{
    /// <inheritdoc />
    public partial class DbInitialPopulation : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Plants",
                columns: table => new
                {
                    Name = table.Column<string>(type: "text", nullable: false),
                    Monograph = table.Column<string>(type: "json", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Plants", x => x.Name);
                });

            // migrationBuilder.CreateTable(
            //     name: "Users",
            //     columns: table => new
            //     {
            //         Id = table.Column<int>(type: "integer", nullable: false)
            //             .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
            //         Name = table.Column<string>(type: "text", nullable: false)
            //     },
            //     constraints: table =>
            //     {
            //         table.PrimaryKey("PK_Users", x => x.Id);
            //     });

            migrationBuilder.CreateTable(
                name: "TermDocumentWeights",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Term = table.Column<string>(type: "text", nullable: false),
                    TermCount = table.Column<int>(type: "integer", nullable: false),
                    PlantName = table.Column<string>(type: "text", nullable: false),
                    TotalWords = table.Column<int>(type: "integer", nullable: false),
                    Value = table.Column<float>(type: "real", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TermDocumentWeights", x => x.Id);
                    table.ForeignKey(
                        name: "FK_TermDocumentWeights_Plants_PlantName",
                        column: x => x.PlantName,
                        principalTable: "Plants",
                        principalColumn: "Name",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Plants",
                columns: new[] { "Name", "Monograph" },
                values: new object[,]
                {
                    { "Abey", "{\"genus\":\"Jacaranda\",\"subsp\":\"\",\"f\":\"\",\"species\":\"coerulea\",\"authors\":\"(L.) Griseb.\",\"family\":\"Bignoniáceas\",\"var\":\"\",\"subfamily\":\"\",\"Sy\":[\"Bignonia coerulea L.\",\"Jacaranda bahamensis R. Br\"],\"Vul\":[\"Abey macho (Cuba)\",\"boxwood (Estados Unidos)\"],\"Hab\":\"Árbol pequeño; se encuentra en las costas, en los terrenos calcáreos pedregosos y en montes bajos, de todas las provincias; pero solo es algo abundante en Camagüey.\",\"Des\":\"Árbol que alcanza  una altura máxima de unos 12 m, con el follaje lampiño. Hojas opuestas, paribipinnadas, pecioladas, a menudo de 3 dm de largo; pennas de 4 a 13 pares, pecioluladas; folíolos de 17 a 35, oblicuamente oblongos, sésiles, de 1 a 2,5 cm de largo; agudos en el ápice, estrechados en la base. Inflorescencia en panículas vistosas, multifloras, de 1 a 7 dm de largo; puberulentas. Flores azules o violetas; pedúnculos cortos. Cáliz campanulado o tubuloso-campanulado, 5-dentado, puberulento, de 5 a 6 mm de largo, sus dientes triangulares, agudos. Corola puberulenta, oblicuamente funeliforme, como de 4 cm de largo, expandida en la parte alta; el limbo algo 2-labiado, con anteras lampiñas; estaminodios poco más o menos del largo de los estambres, claviformes, comúnmente vellosos. Ovario 2-locular, sésil; óvulos dispuestos en 1 o 2 series. Cápsula oval, lampiña, de 4 a 6 cm de largo, emarginada; comprimida, con dehiscencia loculicida, sus aplanadas valvas coriáceas, o leñosas. Semillas planas, aladas.\",\"Cmp\":\"\",\"Use\":\"Las hojas y las ramas.\",\"Pro\":\"\",\"App\":\"En Camagüey y en Oriente usan esta planta para baños antisépticos contra los granos y eczemas. Con el mismo fin se usa en Camagüey otra especie nativa, que crece en los lugares más áridos de las sabanas al norte de la provincia, llamada vulgarmente sibanicú, Jaracanda Cowelli Britton & Wilson. Este es un arbusto de follaje muy fino y folíolos muy pequeños. Se cultiva también en Cuba, con el nombre de framboyán azul, una especie brasileña empleada como ornamental, la Jacaranda filicifolia D. Don, cuyas hojas se usan en Colombia, donde la llaman gualanday, para curar las afecciones sifilíticas. La raíz es diaforética y la corteza emetocátartica. 82 A Otra especie de bignoniácea, cultivada como ornamental por sus bellas flores rojas, es la espatodea, Spathodea campanulata Beauv., cuya corteza se emplea en Colombia como astringente para combatir la diarrea y la disentería. Se dice que el agua contenida en sus botones florales es tónica. A esta planta la llaman en Colombia tulipán rojo.\",\"Cul\":\"\",\"Bib\":[\"Pérez Arbelaez, Enrique: Plantas medicinales y venenosas de Colombia, pp. 257-258, 1937.\"]}" },
                    { "Abrojo", "{\"genus\":\"Tribulus\",\"subsp\":\"\",\"f\":\"\",\"species\":\"cistoides\",\"authors\":\"L.\",\"family\":\"Zigofiláceas\",\"var\":\"\",\"subfamily\":\"\",\"Sy\":[\"Tribulus terrestris cistoides Oliver\"],\"Vul\":[\"Abrojo (Puerto Rico)\",\"large yellow calthrop (Estados Unidos)\"],\"Hab\":\"Yerba rastrera muy común en todas las costas altas y arenosas donde forma extensos colchones. Existe también en las demás Antillas Mayores, las Islas Vírgenes y Antillas Menores, hacia el sur hasta Martinica, el este de los Estados Unidos, América tropical continental y en los trópicos del Viejo Mundo.\",\"Des\":\"Yerba perenne, raíces gruesas, leñosas; tallos difusos, procumbentes, de 3 a 10 dm de largo, pubescentes, que se vuelven lampiños. Hojas paripennadas, de 1 a 5 cm de largo; folíolos de 6 a 8 pares, oblicuamente oblongos o elípticos, agudos u obtusos y mucronulados, de 14 a 15 mm de largo, sedoso-pubescentes debajo; estípulas aleznadas, de 5 a 8 mm de largo. Flores axilares amarillas; pedúnculos poco más o menos del largo de las hojas, solitarios. Sépalos 5; persistentes, lanceolados, de la mitad del largo de los pétalos. Pétalos 5, caducos, como de 2 cm de largo. Estambres 10, los alternos algo más largos. Ovario sésil, 5-lobado, 5-locular, peludo, los pelos erectos; estilo corto; estigma 5-aristado; óvulos de 3 a 10 en cada cavidad. Carpelos péndulos, tuberculados, cada uno con 2 robustas espinas divergentes y, a veces con varias más pequeñas esparcidas. Fruto 5-angular, espinoso, que se abre en 5 segmentos, con 3 a 5 semillas.\",\"Cmp\":\"\",\"Use\":\"Las hojas y las raíces.\",\"Pro\":\"\",\"App\":\"Con las hojas pulverizadas se hacen cataplasmas madurativas. Las raíces son corroborantes, como tales estomáquicas y diuréticas. Los cocimientos de las semillas son útiles para casos de diarrea. Indicaciones: como diurético, tomar una taza de cocimiento en ayunas.\",\"Cul\":\"\",\"Bib\":[\"Álvarez Gonzalez, P.: Yerbas medicinales, pp. 34 y 35, 1963.\",\"Cabrera, Luis G.: Plantas curativas de México, Ed. Cicerón, México, 1958.\",\"Gómez de la Maza, M.: Ensayos de Farmacofitología cubana, Lxiii, p. 34, 1889.\",\"Grosourdy, Renato de: El médico botánico criollo, no. 379, p. 226, Librería Francisco Brachet, París, 1864.\"]}" },
                    { "Achicoria*", "{\"genus\":\"Cichorium\",\"subsp\":\"\",\"f\":\"\",\"species\":\"intibus\",\"authors\":\"L.\",\"family\":\"Compuestas\",\"var\":\"\",\"subfamily\":\"\",\"Sy\":[],\"Vul\":[\"Chicoria (España)\",\"chicorée (Francia)\",\"chicory (Estados Unidos)\",\"succory (Estados Unidos)\"],\"Hab\":\"La achicoria es una planta europea de la región mediterránea. En España crece silvestre, al borde de los caminos y en sitios incultos de tierras bajas y de las montañas. También se ha propagado en los Estados Unidos.\",\"Des\":\"Es una planta vivaz, de raíz profunda, muy ramificada y de 0,90 a 1,80 m de altura; hojas oblongas, oblanceoladas, o lanceoladas más o menos abrazadoras; las inferiores casi enteras, las superiores se vuelven algunas veces brácteas, por lo común más cortas que las cabezuelas.\",\"Cmp\":\"\",\"Use\":\"La raíz, las hojas y las cabezuelas.\",\"Pro\":\"Tónica, aperitiva y estomacal.\",\"App\":\"Las hojas y la flor se emplean en infusión tanto secas, como frescas. Dan una tisana amarga que sienta bien después de una comida copiosa. La raíz se usa para el mismo fin.\",\"Cul\":\"\",\"Bib\":[\"Font Quer: Diccionario de Botánica, p. 128, 1953.\",\"Grosourdy: Plantas útiles del Nuevo Mundo, p. 203, 1875.\"]}" }
                });

            // migrationBuilder.InsertData(
            //     table: "Users",
            //     columns: new[] { "Id", "Name" },
            //     values: new object[] { 1, "Admin" });

            migrationBuilder.InsertData(
                table: "TermDocumentWeights",
                columns: new[] { "Id", "PlantName", "Term", "TermCount", "TotalWords", "Value" },
                values: new object[,]
                {
                    { 1, "Abey", "abey", 2, 213, 0f },
                    { 2, "Abey", "jacaranda", 3, 213, 0f },
                    { 3, "Abey", "coerulea", 2, 213, 0f },
                    { 4, "Abey", "griseb", 1, 213, 0f },
                    { 5, "Abey", "bignoniáceas", 1, 213, 0f },
                    { 6, "Abey", "bignonia", 1, 213, 0f },
                    { 7, "Abey", "bahamensis", 1, 213, 0f },
                    { 8, "Abey", "br", 1, 213, 0f },
                    { 9, "Abey", "macho", 1, 213, 0f },
                    { 10, "Abey", "cuba", 2, 213, 0f },
                    { 11, "Abey", "boxwood", 1, 213, 0f },
                    { 12, "Abey", "estados", 1, 213, 0f },
                    { 13, "Abey", "unidos", 1, 213, 0f },
                    { 14, "Abey", "árbol", 2, 213, 0f },
                    { 15, "Abey", "pequeño", 1, 213, 0f },
                    { 16, "Abey", "encuentra", 1, 213, 0f },
                    { 17, "Abey", "costas", 1, 213, 0f },
                    { 18, "Abey", "terrenos", 1, 213, 0f },
                    { 19, "Abey", "calcáreos", 1, 213, 0f },
                    { 20, "Abey", "pedregosos", 1, 213, 0f },
                    { 21, "Abey", "montes", 1, 213, 0f },
                    { 22, "Abey", "bajos", 1, 213, 0f },
                    { 23, "Abey", "todas", 1, 213, 0f },
                    { 24, "Abey", "provincias", 1, 213, 0f },
                    { 25, "Abey", "solo", 1, 213, 0f },
                    { 26, "Abey", "abundante", 1, 213, 0f },
                    { 27, "Abey", "alcanza", 1, 213, 0f },
                    { 28, "Abey", "altura", 1, 213, 0f },
                    { 29, "Abey", "máxima", 1, 213, 0f },
                    { 30, "Abey", "follaje", 2, 213, 0f },
                    { 31, "Abey", "lampiño", 1, 213, 0f },
                    { 32, "Abey", "hojas", 3, 213, 0f },
                    { 33, "Abey", "opuestas", 1, 213, 0f },
                    { 34, "Abey", "paribipinnadas", 1, 213, 0f },
                    { 35, "Abey", "pecioladas", 1, 213, 0f },
                    { 36, "Abey", "menudo", 1, 213, 0f },
                    { 37, "Abey", "dm", 2, 213, 0f },
                    { 38, "Abey", "largo", 7, 213, 0f },
                    { 39, "Abey", "pennas", 1, 213, 0f },
                    { 40, "Abey", "pares", 1, 213, 0f },
                    { 41, "Abey", "pecioluladas", 1, 213, 0f },
                    { 42, "Abey", "folíolos", 2, 213, 0f },
                    { 43, "Abey", "oblicuamente", 2, 213, 0f },
                    { 44, "Abey", "oblongos", 1, 213, 0f },
                    { 45, "Abey", "sésiles", 1, 213, 0f },
                    { 46, "Abey", "cm", 3, 213, 0f },
                    { 47, "Abey", "agudos", 2, 213, 0f },
                    { 48, "Abey", "ápice", 1, 213, 0f },
                    { 49, "Abey", "estrechados", 1, 213, 0f },
                    { 50, "Abey", "base", 1, 213, 0f },
                    { 51, "Abey", "inflorescencia", 1, 213, 0f },
                    { 52, "Abey", "panículas", 1, 213, 0f },
                    { 53, "Abey", "vistosas", 1, 213, 0f },
                    { 54, "Abey", "multifloras", 1, 213, 0f },
                    { 55, "Abey", "puberulentas", 1, 213, 0f },
                    { 56, "Abey", "flores", 2, 213, 0f },
                    { 57, "Abey", "azules", 1, 213, 0f },
                    { 58, "Abey", "violetas", 1, 213, 0f },
                    { 59, "Abey", "pedúnculos", 1, 213, 0f },
                    { 60, "Abey", "cortos", 1, 213, 0f },
                    { 61, "Abey", "cáliz", 1, 213, 0f },
                    { 62, "Abey", "campanulado", 1, 213, 0f },
                    { 63, "Abey", "puberulento", 1, 213, 0f },
                    { 64, "Abey", "mm", 1, 213, 0f },
                    { 65, "Abey", "dientes", 1, 213, 0f },
                    { 66, "Abey", "triangulares", 1, 213, 0f },
                    { 67, "Abey", "corola", 1, 213, 0f },
                    { 68, "Abey", "puberulenta", 1, 213, 0f },
                    { 69, "Abey", "funeliforme", 1, 213, 0f },
                    { 70, "Abey", "expandida", 1, 213, 0f },
                    { 71, "Abey", "parte", 1, 213, 0f },
                    { 72, "Abey", "alta", 1, 213, 0f },
                    { 73, "Abey", "limbo", 1, 213, 0f },
                    { 74, "Abey", "anteras", 1, 213, 0f },
                    { 75, "Abey", "lampiñas", 1, 213, 0f },
                    { 76, "Abey", "estaminodios", 1, 213, 0f },
                    { 77, "Abey", "más", 2, 213, 0f },
                    { 78, "Abey", "menos", 1, 213, 0f },
                    { 79, "Abey", "estambres", 1, 213, 0f },
                    { 80, "Abey", "claviformes", 1, 213, 0f },
                    { 81, "Abey", "comúnmente", 1, 213, 0f },
                    { 82, "Abey", "vellosos", 1, 213, 0f },
                    { 83, "Abey", "ovario", 1, 213, 0f },
                    { 84, "Abey", "sésil", 1, 213, 0f },
                    { 85, "Abey", "óvulos", 1, 213, 0f },
                    { 86, "Abey", "dispuestos", 1, 213, 0f },
                    { 87, "Abey", "series", 1, 213, 0f },
                    { 88, "Abey", "cápsula", 1, 213, 0f },
                    { 89, "Abey", "oval", 1, 213, 0f },
                    { 90, "Abey", "lampiña", 1, 213, 0f },
                    { 91, "Abey", "emarginada", 1, 213, 0f },
                    { 92, "Abey", "comprimida", 1, 213, 0f },
                    { 93, "Abey", "dehiscencia", 1, 213, 0f },
                    { 94, "Abey", "loculicida", 1, 213, 0f },
                    { 95, "Abey", "aplanadas", 1, 213, 0f },
                    { 96, "Abey", "valvas", 1, 213, 0f },
                    { 97, "Abey", "coriáceas", 1, 213, 0f },
                    { 98, "Abey", "leñosas", 1, 213, 0f },
                    { 99, "Abey", "semillas", 1, 213, 0f },
                    { 100, "Abey", "planas", 1, 213, 0f },
                    { 101, "Abey", "aladas", 1, 213, 0f },
                    { 102, "Abey", "ramas", 1, 213, 0f },
                    { 103, "Abey", "oriente", 1, 213, 0f },
                    { 104, "Abey", "usan", 2, 213, 0f },
                    { 105, "Abey", "planta", 2, 213, 0f },
                    { 106, "Abey", "baños", 1, 213, 0f },
                    { 107, "Abey", "antisépticos", 1, 213, 0f },
                    { 108, "Abey", "granos", 1, 213, 0f },
                    { 109, "Abey", "eczemas", 1, 213, 0f },
                    { 110, "Abey", "mismo", 1, 213, 0f },
                    { 111, "Abey", "fin", 1, 213, 0f },
                    { 112, "Abey", "usa", 1, 213, 0f },
                    { 113, "Abey", "especie", 3, 213, 0f },
                    { 114, "Abey", "nativa", 1, 213, 0f },
                    { 115, "Abey", "crece", 1, 213, 0f },
                    { 116, "Abey", "lugares", 1, 213, 0f },
                    { 117, "Abey", "áridos", 1, 213, 0f },
                    { 118, "Abey", "sabanas", 1, 213, 0f },
                    { 119, "Abey", "norte", 1, 213, 0f },
                    { 120, "Abey", "provincia", 1, 213, 0f },
                    { 121, "Abey", "llamada", 1, 213, 0f },
                    { 122, "Abey", "vulgarmente", 1, 213, 0f },
                    { 123, "Abey", "sibanicú", 1, 213, 0f },
                    { 124, "Abey", "jaracanda", 1, 213, 0f },
                    { 125, "Abey", "cowelli", 1, 213, 0f },
                    { 126, "Abey", "britton", 1, 213, 0f },
                    { 127, "Abey", "wilson", 1, 213, 0f },
                    { 128, "Abey", "arbusto", 1, 213, 0f },
                    { 129, "Abey", "fino", 1, 213, 0f },
                    { 130, "Abey", "pequeños", 1, 213, 0f },
                    { 131, "Abey", "cultiva", 1, 213, 0f },
                    { 132, "Abey", "también", 1, 213, 0f },
                    { 133, "Abey", "nombre", 1, 213, 0f },
                    { 134, "Abey", "framboyán", 1, 213, 0f },
                    { 135, "Abey", "azul", 1, 213, 0f },
                    { 136, "Abey", "brasileña", 1, 213, 0f },
                    { 137, "Abey", "empleada", 1, 213, 0f },
                    { 138, "Abey", "ornamental", 2, 213, 0f },
                    { 139, "Abey", "filicifolia", 1, 213, 0f },
                    { 140, "Abey", "don", 1, 213, 0f },
                    { 141, "Abey", "cuyas", 1, 213, 0f },
                    { 142, "Abey", "colombia", 4, 213, 0f },
                    { 143, "Abey", "llaman", 2, 213, 0f },
                    { 144, "Abey", "gualanday", 1, 213, 0f },
                    { 145, "Abey", "curar", 1, 213, 0f },
                    { 146, "Abey", "afecciones", 1, 213, 0f },
                    { 147, "Abey", "sifilíticas", 1, 213, 0f },
                    { 148, "Abey", "raíz", 1, 213, 0f },
                    { 149, "Abey", "diaforética", 1, 213, 0f },
                    { 150, "Abey", "corteza", 2, 213, 0f },
                    { 151, "Abey", "emetocátartica", 1, 213, 0f },
                    { 152, "Abey", "bignoniácea", 1, 213, 0f },
                    { 153, "Abey", "cultivada", 1, 213, 0f },
                    { 154, "Abey", "bellas", 1, 213, 0f },
                    { 155, "Abey", "rojas", 1, 213, 0f },
                    { 156, "Abey", "espatodea", 1, 213, 0f },
                    { 157, "Abey", "spathodea", 1, 213, 0f },
                    { 158, "Abey", "campanulata", 1, 213, 0f },
                    { 159, "Abey", "beauv", 1, 213, 0f },
                    { 160, "Abey", "cuya", 1, 213, 0f },
                    { 161, "Abey", "emplea", 1, 213, 0f },
                    { 162, "Abey", "astringente", 1, 213, 0f },
                    { 163, "Abey", "combatir", 1, 213, 0f },
                    { 164, "Abey", "diarrea", 1, 213, 0f },
                    { 165, "Abey", "disentería", 1, 213, 0f },
                    { 166, "Abey", "dice", 1, 213, 0f },
                    { 167, "Abey", "agua", 1, 213, 0f },
                    { 168, "Abey", "contenida", 1, 213, 0f },
                    { 169, "Abey", "botones", 1, 213, 0f },
                    { 170, "Abey", "florales", 1, 213, 0f },
                    { 171, "Abey", "tónica", 1, 213, 0f },
                    { 172, "Abey", "tulipán", 1, 213, 0f },
                    { 173, "Abey", "rojo", 1, 213, 0f },
                    { 174, "Abey", "pérez", 1, 213, 0f },
                    { 175, "Abey", "arbelaez", 1, 213, 0f },
                    { 176, "Abey", "enrique", 1, 213, 0f },
                    { 177, "Abey", "plantas", 1, 213, 0f },
                    { 178, "Abey", "medicinales", 1, 213, 0f },
                    { 179, "Abey", "venenosas", 1, 213, 0f },
                    { 180, "Abey", "pp", 1, 213, 0f },
                    { 181, "Abrojo", "abrojo", 2, 182, 0f },
                    { 182, "Abrojo", "tribulus", 2, 182, 0f },
                    { 183, "Abrojo", "cistoides", 2, 182, 0f },
                    { 184, "Abrojo", "zigofiláceas", 1, 182, 0f },
                    { 185, "Abrojo", "terrestris", 1, 182, 0f },
                    { 186, "Abrojo", "oliver", 1, 182, 0f },
                    { 187, "Abrojo", "puerto", 1, 182, 0f },
                    { 188, "Abrojo", "rico", 1, 182, 0f },
                    { 189, "Abrojo", "large", 1, 182, 0f },
                    { 190, "Abrojo", "yellow", 1, 182, 0f },
                    { 191, "Abrojo", "calthrop", 1, 182, 0f },
                    { 192, "Abrojo", "estados", 2, 182, 0f },
                    { 193, "Abrojo", "unidos", 2, 182, 0f },
                    { 194, "Abrojo", "yerba", 2, 182, 0f },
                    { 195, "Abrojo", "rastrera", 1, 182, 0f },
                    { 196, "Abrojo", "común", 1, 182, 0f },
                    { 197, "Abrojo", "todas", 1, 182, 0f },
                    { 198, "Abrojo", "costas", 1, 182, 0f },
                    { 199, "Abrojo", "altas", 1, 182, 0f },
                    { 200, "Abrojo", "arenosas", 1, 182, 0f },
                    { 201, "Abrojo", "forma", 1, 182, 0f },
                    { 202, "Abrojo", "extensos", 1, 182, 0f },
                    { 203, "Abrojo", "colchones", 1, 182, 0f },
                    { 204, "Abrojo", "existe", 1, 182, 0f },
                    { 205, "Abrojo", "también", 1, 182, 0f },
                    { 206, "Abrojo", "demás", 1, 182, 0f },
                    { 207, "Abrojo", "antillas", 2, 182, 0f },
                    { 208, "Abrojo", "mayores", 1, 182, 0f },
                    { 209, "Abrojo", "islas", 1, 182, 0f },
                    { 210, "Abrojo", "vírgenes", 1, 182, 0f },
                    { 211, "Abrojo", "menores", 1, 182, 0f },
                    { 212, "Abrojo", "hacia", 1, 182, 0f },
                    { 213, "Abrojo", "sur", 1, 182, 0f },
                    { 214, "Abrojo", "martinica", 1, 182, 0f },
                    { 215, "Abrojo", "américa", 1, 182, 0f },
                    { 216, "Abrojo", "tropical", 1, 182, 0f },
                    { 217, "Abrojo", "continental", 1, 182, 0f },
                    { 218, "Abrojo", "trópicos", 1, 182, 0f },
                    { 219, "Abrojo", "viejo", 1, 182, 0f },
                    { 220, "Abrojo", "mundo", 1, 182, 0f },
                    { 221, "Abrojo", "perenne", 1, 182, 0f },
                    { 222, "Abrojo", "raíces", 3, 182, 0f },
                    { 223, "Abrojo", "gruesas", 1, 182, 0f },
                    { 224, "Abrojo", "leñosas", 1, 182, 0f },
                    { 225, "Abrojo", "tallos", 1, 182, 0f },
                    { 226, "Abrojo", "difusos", 1, 182, 0f },
                    { 227, "Abrojo", "procumbentes", 1, 182, 0f },
                    { 228, "Abrojo", "dm", 1, 182, 0f },
                    { 229, "Abrojo", "largo", 7, 182, 0f },
                    { 230, "Abrojo", "pubescentes", 1, 182, 0f },
                    { 231, "Abrojo", "vuelven", 1, 182, 0f },
                    { 232, "Abrojo", "lampiños", 1, 182, 0f },
                    { 233, "Abrojo", "hojas", 4, 182, 0f },
                    { 234, "Abrojo", "paripennadas", 1, 182, 0f },
                    { 235, "Abrojo", "cm", 2, 182, 0f },
                    { 236, "Abrojo", "folíolos", 1, 182, 0f },
                    { 237, "Abrojo", "pares", 1, 182, 0f },
                    { 238, "Abrojo", "oblicuamente", 1, 182, 0f },
                    { 239, "Abrojo", "oblongos", 1, 182, 0f },
                    { 240, "Abrojo", "elípticos", 1, 182, 0f },
                    { 241, "Abrojo", "agudos", 1, 182, 0f },
                    { 242, "Abrojo", "obtusos", 1, 182, 0f },
                    { 243, "Abrojo", "mucronulados", 1, 182, 0f },
                    { 244, "Abrojo", "mm", 2, 182, 0f },
                    { 245, "Abrojo", "debajo", 1, 182, 0f },
                    { 246, "Abrojo", "estípulas", 1, 182, 0f },
                    { 247, "Abrojo", "aleznadas", 1, 182, 0f },
                    { 248, "Abrojo", "flores", 1, 182, 0f },
                    { 249, "Abrojo", "axilares", 1, 182, 0f },
                    { 250, "Abrojo", "amarillas", 1, 182, 0f },
                    { 251, "Abrojo", "pedúnculos", 1, 182, 0f },
                    { 252, "Abrojo", "más", 3, 182, 0f },
                    { 253, "Abrojo", "menos", 1, 182, 0f },
                    { 254, "Abrojo", "solitarios", 1, 182, 0f },
                    { 255, "Abrojo", "sépalos", 1, 182, 0f },
                    { 256, "Abrojo", "persistentes", 1, 182, 0f },
                    { 257, "Abrojo", "lanceolados", 1, 182, 0f },
                    { 258, "Abrojo", "mitad", 1, 182, 0f },
                    { 259, "Abrojo", "pétalos", 2, 182, 0f },
                    { 260, "Abrojo", "caducos", 1, 182, 0f },
                    { 261, "Abrojo", "estambres", 1, 182, 0f },
                    { 262, "Abrojo", "alternos", 1, 182, 0f },
                    { 263, "Abrojo", "largos", 1, 182, 0f },
                    { 264, "Abrojo", "ovario", 1, 182, 0f },
                    { 265, "Abrojo", "sésil", 1, 182, 0f },
                    { 266, "Abrojo", "peludo", 1, 182, 0f },
                    { 267, "Abrojo", "pelos", 1, 182, 0f },
                    { 268, "Abrojo", "erectos", 1, 182, 0f },
                    { 269, "Abrojo", "estilo", 1, 182, 0f },
                    { 270, "Abrojo", "corto", 1, 182, 0f },
                    { 271, "Abrojo", "estigma", 1, 182, 0f },
                    { 272, "Abrojo", "óvulos", 1, 182, 0f },
                    { 273, "Abrojo", "cada", 2, 182, 0f },
                    { 274, "Abrojo", "cavidad", 1, 182, 0f },
                    { 275, "Abrojo", "carpelos", 1, 182, 0f },
                    { 276, "Abrojo", "péndulos", 1, 182, 0f },
                    { 277, "Abrojo", "tuberculados", 1, 182, 0f },
                    { 278, "Abrojo", "robustas", 1, 182, 0f },
                    { 279, "Abrojo", "espinas", 1, 182, 0f },
                    { 280, "Abrojo", "divergentes", 1, 182, 0f },
                    { 281, "Abrojo", "veces", 1, 182, 0f },
                    { 282, "Abrojo", "varias", 1, 182, 0f },
                    { 283, "Abrojo", "pequeñas", 1, 182, 0f },
                    { 284, "Abrojo", "esparcidas", 1, 182, 0f },
                    { 285, "Abrojo", "fruto", 1, 182, 0f },
                    { 286, "Abrojo", "espinoso", 1, 182, 0f },
                    { 287, "Abrojo", "abre", 1, 182, 0f },
                    { 288, "Abrojo", "segmentos", 1, 182, 0f },
                    { 289, "Abrojo", "semillas", 2, 182, 0f },
                    { 290, "Abrojo", "pulverizadas", 1, 182, 0f },
                    { 291, "Abrojo", "hacen", 1, 182, 0f },
                    { 292, "Abrojo", "cataplasmas", 1, 182, 0f },
                    { 293, "Abrojo", "madurativas", 1, 182, 0f },
                    { 294, "Abrojo", "son", 2, 182, 0f },
                    { 295, "Abrojo", "corroborantes", 1, 182, 0f },
                    { 296, "Abrojo", "tales", 1, 182, 0f },
                    { 297, "Abrojo", "estomáquicas", 1, 182, 0f },
                    { 298, "Abrojo", "diuréticas", 1, 182, 0f },
                    { 299, "Abrojo", "cocimientos", 1, 182, 0f },
                    { 300, "Abrojo", "útiles", 1, 182, 0f },
                    { 301, "Abrojo", "casos", 1, 182, 0f },
                    { 302, "Abrojo", "diarrea", 1, 182, 0f },
                    { 303, "Abrojo", "indicaciones", 1, 182, 0f },
                    { 304, "Abrojo", "diurético", 1, 182, 0f },
                    { 305, "Abrojo", "tomar", 1, 182, 0f },
                    { 306, "Abrojo", "taza", 1, 182, 0f },
                    { 307, "Abrojo", "cocimiento", 1, 182, 0f },
                    { 308, "Abrojo", "ayunas", 1, 182, 0f },
                    { 309, "Abrojo", "álvarez", 1, 182, 0f },
                    { 310, "Abrojo", "gonzalez", 1, 182, 0f },
                    { 311, "Abrojo", "yerbas", 1, 182, 0f },
                    { 312, "Abrojo", "medicinales", 1, 182, 0f },
                    { 313, "Abrojo", "pp", 1, 182, 0f },
                    { 314, "Abrojo", "cabrera", 1, 182, 0f },
                    { 315, "Abrojo", "luis", 1, 182, 0f },
                    { 316, "Abrojo", "plantas", 1, 182, 0f },
                    { 317, "Abrojo", "curativas", 1, 182, 0f },
                    { 318, "Abrojo", "méxico", 2, 182, 0f },
                    { 319, "Abrojo", "ed", 1, 182, 0f },
                    { 320, "Abrojo", "cicerón", 1, 182, 0f },
                    { 321, "Abrojo", "gómez", 1, 182, 0f },
                    { 322, "Abrojo", "maza", 1, 182, 0f },
                    { 323, "Abrojo", "ensayos", 1, 182, 0f },
                    { 324, "Abrojo", "farmacofitología", 1, 182, 0f },
                    { 325, "Abrojo", "cubana", 1, 182, 0f },
                    { 326, "Abrojo", "lxiii", 1, 182, 0f },
                    { 327, "Abrojo", "grosourdy", 1, 182, 0f },
                    { 328, "Abrojo", "renato", 1, 182, 0f },
                    { 329, "Abrojo", "médico", 1, 182, 0f },
                    { 330, "Abrojo", "botánico", 1, 182, 0f },
                    { 331, "Abrojo", "criollo", 1, 182, 0f },
                    { 332, "Abrojo", "librería", 1, 182, 0f },
                    { 333, "Abrojo", "francisco", 1, 182, 0f },
                    { 334, "Abrojo", "brachet", 1, 182, 0f },
                    { 335, "Abrojo", "parís", 1, 182, 0f },
                    { 336, "Achicoria*", "achicoria*", 1, 91, 0f },
                    { 337, "Achicoria*", "cichorium", 1, 91, 0f },
                    { 338, "Achicoria*", "intibus", 1, 91, 0f },
                    { 339, "Achicoria*", "compuestas", 1, 91, 0f },
                    { 340, "Achicoria*", "chicoria", 1, 91, 0f },
                    { 341, "Achicoria*", "españa", 2, 91, 0f },
                    { 342, "Achicoria*", "chicorée", 1, 91, 0f },
                    { 343, "Achicoria*", "francia", 1, 91, 0f },
                    { 344, "Achicoria*", "chicory", 1, 91, 0f },
                    { 345, "Achicoria*", "estados", 3, 91, 0f },
                    { 346, "Achicoria*", "unidos", 3, 91, 0f },
                    { 347, "Achicoria*", "succory", 1, 91, 0f },
                    { 348, "Achicoria*", "achicoria", 1, 91, 0f },
                    { 349, "Achicoria*", "planta", 2, 91, 0f },
                    { 350, "Achicoria*", "europea", 1, 91, 0f },
                    { 351, "Achicoria*", "región", 1, 91, 0f },
                    { 352, "Achicoria*", "mediterránea", 1, 91, 0f },
                    { 353, "Achicoria*", "crece", 1, 91, 0f },
                    { 354, "Achicoria*", "silvestre", 1, 91, 0f },
                    { 355, "Achicoria*", "borde", 1, 91, 0f },
                    { 356, "Achicoria*", "caminos", 1, 91, 0f },
                    { 357, "Achicoria*", "sitios", 1, 91, 0f },
                    { 358, "Achicoria*", "incultos", 1, 91, 0f },
                    { 359, "Achicoria*", "tierras", 1, 91, 0f },
                    { 360, "Achicoria*", "bajas", 1, 91, 0f },
                    { 361, "Achicoria*", "montañas", 1, 91, 0f },
                    { 362, "Achicoria*", "también", 1, 91, 0f },
                    { 363, "Achicoria*", "propagado", 1, 91, 0f },
                    { 364, "Achicoria*", "vivaz", 1, 91, 0f },
                    { 365, "Achicoria*", "raíz", 3, 91, 0f },
                    { 366, "Achicoria*", "profunda", 1, 91, 0f },
                    { 367, "Achicoria*", "ramificada", 1, 91, 0f },
                    { 368, "Achicoria*", "altura", 1, 91, 0f },
                    { 369, "Achicoria*", "hojas", 3, 91, 0f },
                    { 370, "Achicoria*", "oblongas", 1, 91, 0f },
                    { 371, "Achicoria*", "oblanceoladas", 1, 91, 0f },
                    { 372, "Achicoria*", "lanceoladas", 1, 91, 0f },
                    { 373, "Achicoria*", "más", 2, 91, 0f },
                    { 374, "Achicoria*", "menos", 1, 91, 0f },
                    { 375, "Achicoria*", "abrazadoras", 1, 91, 0f },
                    { 376, "Achicoria*", "inferiores", 1, 91, 0f },
                    { 377, "Achicoria*", "casi", 1, 91, 0f },
                    { 378, "Achicoria*", "enteras", 1, 91, 0f },
                    { 379, "Achicoria*", "superiores", 1, 91, 0f },
                    { 380, "Achicoria*", "vuelven", 1, 91, 0f },
                    { 381, "Achicoria*", "algunas", 1, 91, 0f },
                    { 382, "Achicoria*", "veces", 1, 91, 0f },
                    { 383, "Achicoria*", "brácteas", 1, 91, 0f },
                    { 384, "Achicoria*", "común", 1, 91, 0f },
                    { 385, "Achicoria*", "cortas", 1, 91, 0f },
                    { 386, "Achicoria*", "cabezuelas", 2, 91, 0f },
                    { 387, "Achicoria*", "tónica", 1, 91, 0f },
                    { 388, "Achicoria*", "aperitiva", 1, 91, 0f },
                    { 389, "Achicoria*", "estomacal", 1, 91, 0f },
                    { 390, "Achicoria*", "flor", 1, 91, 0f },
                    { 391, "Achicoria*", "emplean", 1, 91, 0f },
                    { 392, "Achicoria*", "infusión", 1, 91, 0f },
                    { 393, "Achicoria*", "secas", 1, 91, 0f },
                    { 394, "Achicoria*", "frescas", 1, 91, 0f },
                    { 395, "Achicoria*", "dan", 1, 91, 0f },
                    { 396, "Achicoria*", "tisana", 1, 91, 0f },
                    { 397, "Achicoria*", "amarga", 1, 91, 0f },
                    { 398, "Achicoria*", "sienta", 1, 91, 0f },
                    { 399, "Achicoria*", "bien", 1, 91, 0f },
                    { 400, "Achicoria*", "después", 1, 91, 0f },
                    { 401, "Achicoria*", "comida", 1, 91, 0f },
                    { 402, "Achicoria*", "copiosa", 1, 91, 0f },
                    { 403, "Achicoria*", "usa", 1, 91, 0f },
                    { 404, "Achicoria*", "mismo", 1, 91, 0f },
                    { 405, "Achicoria*", "fin", 1, 91, 0f },
                    { 406, "Achicoria*", "font", 1, 91, 0f },
                    { 407, "Achicoria*", "quer", 1, 91, 0f },
                    { 408, "Achicoria*", "diccionario", 1, 91, 0f },
                    { 409, "Achicoria*", "botánica", 1, 91, 0f },
                    { 410, "Achicoria*", "grosourdy", 1, 91, 0f },
                    { 411, "Achicoria*", "plantas", 1, 91, 0f },
                    { 412, "Achicoria*", "útiles", 1, 91, 0f },
                    { 413, "Achicoria*", "nuevo", 1, 91, 0f },
                    { 414, "Achicoria*", "mundo", 1, 91, 0f }
                });

            migrationBuilder.CreateIndex(
                name: "IX_TermDocumentWeights_PlantName",
                table: "TermDocumentWeights",
                column: "PlantName");

            migrationBuilder.CreateIndex(
                name: "IX_TermDocumentWeights_Term_PlantName",
                table: "TermDocumentWeights",
                columns: new[] { "Term", "PlantName" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "TermDocumentWeights");

            migrationBuilder.DropTable(
                name: "Users");

            migrationBuilder.DropTable(
                name: "Plants");
        }
    }
}
