import { useState } from 'react';

const useTextSearch = () => {
    const [loading, setLoading] = useState<boolean>(false);
    const [monographs, setMonographs] = useState<Monograph[]>([]);

    const handleSearch: (data: { query?: string }) => void = async (data) => {
        setLoading(true);
        console.log(data.query);
        await new Promise((f) => setTimeout(f, 5000));
        setMonographs([
            {
                id: 0,
                name: 'Moruno abey',
                genus: 'Jacaranda',
                subsp: '',
                f: '',
                species: 'coerulea',
                authors: '(L.) Griseb',
                family: '',
                var: '',
                subfamily: '',
                sy: [],
                vul: [],
                hab: 'Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud. Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud.Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud.Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud.',
                des: '',
                cmp: '',
                use: '',
                pro: '',
                app: '',
                cul: '',
                bib: [],
            },
            {
                id: 0,
                name: 'Moruno abey',
                genus: 'Jacaranda',
                subsp: '',
                f: '',
                species: 'coerulea',
                authors: '(L.) Griseb',
                family: '',
                var: '',
                subfamily: '',
                sy: [],
                vul: [],
                hab: 'Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud. Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud.Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud.Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud.',
                des: '',
                cmp: '',
                use: '',
                pro: '',
                app: '',
                cul: '',
                bib: [],
            },
            {
                id: 0,
                name: 'Moruno abey',
                genus: 'Jacaranda',
                subsp: '',
                f: '',
                species: 'coerulea',
                authors: '(L.) Griseb',
                family: '',
                var: '',
                subfamily: '',
                sy: [],
                vul: [],
                hab: 'Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud. Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud.Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud.Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud.',
                des: '',
                cmp: '',
                use: '',
                pro: '',
                app: '',
                cul: '',
                bib: [],
            },
            {
                id: 0,
                name: 'Moruno abey',
                genus: 'Jacaranda',
                subsp: '',
                f: '',
                species: 'coerulea',
                authors: '(L.) Griseb',
                family: '',
                var: '',
                subfamily: '',
                sy: [],
                vul: [],
                hab: 'Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud. Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud.Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud.Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud.',
                des: '',
                cmp: '',
                use: '',
                pro: '',
                app: '',
                cul: '',
                bib: [],
            },
            {
                id: 0,
                name: 'Moruno abey',
                genus: 'Jacaranda',
                subsp: '',
                f: '',
                species: 'coerulea',
                authors: '(L.) Griseb',
                family: '',
                var: '',
                subfamily: '',
                sy: [],
                vul: [],
                hab: 'Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud. Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud.Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud.Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud.',
                des: '',
                cmp: '',
                use: '',
                pro: '',
                app: '',
                cul: '',
                bib: [],
            },
            {
                id: 0,
                name: 'Moruno abey',
                genus: 'Jacaranda',
                subsp: '',
                f: '',
                species: 'coerulea',
                authors: '(L.) Griseb',
                family: '',
                var: '',
                subfamily: '',
                sy: [],
                vul: [],
                hab: 'Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud. Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud.Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud.Aute proident nostrud esse fugiat veniam commodo adipisicing officia ut proident enim magna aute proident nostrud.',
                des: '',
                cmp: '',
                use: '',
                pro: '',
                app: '',
                cul: '',
                bib: [],
            },
        ]);
        setLoading(false);
    };

    return {
        handleSearch,
        loading,
        monographs,
    };
};

export default useTextSearch;
