export const monographsSeed: Monograph[] = [
    {
      id: 1,
      name: "Abey",
      genus: "Jacaranda",
      subsp: "",
      f: "",
      species: "coerulea",
      authors: "(L.) Griseb.",
      family: "Bignoniáceas",
      var: "",
      subfamily: "",
      sy: ["Bignonia coerulea L.", "Jacaranda bahamensis R. Br"],
      vul: ["Abey macho (Cuba)", "boxwood (EU)"],
      hab: "Árbol pequeño, se encuentra en las costas, en los terrenos calcáreos pedregosos y en montes bajos, de todas las provincias; pero solo es algo abundante en Camagüey.",
      des: "Árbol que alcanza una altura máxima de unos 12 m, con el follaje lampiño...",
      cmp: "",
      use: "Las hojas y las ramas.",
      pro: "",
      app: "En Camagüey y en Oriente usan esta planta para baños antisépticos...",
      cul: "",
      bib: [
        "Pérez Arbelaez, Enrique: Plantas medicinales y venenosas de Colombia, pp. 257-258, 1937.",
      ],
    },
    {
      id: 2,
      name: "Guayaba",
      genus: "Psidium",
      subsp: "",
      f: "",
      species: "guajava",
      authors: "L.",
      family: "Myrtaceae",
      var: "",
      subfamily: "",
      sy: ["Guayava vulgaris A. Rich."],
      vul: ["Guayaba (Cuba)", "Guayabo (MX)"],
      hab: "Árbol o arbusto que crece en terrenos cálidos y húmedos.",
      des: "Árbol de follaje perenne, de unos 6-8 m de altura, hojas opuestas, flores blancas...",
      cmp: "Rica en vitamina C, pectina y antioxidantes.",
      use: "Fruto, hojas y corteza.",
      pro: "Antidiarreico, antioxidante.",
      app: "Se utiliza para tratar infecciones digestivas y como astringente.",
      cul: "Se cultiva en zonas tropicales y subtropicales.",
      bib: ["Roig y Mesa, Tomás: Plantas Medicinales, 1927."],
    },
    {
      id: 3,
      name: "Aloe Vera",
      genus: "Aloe",
      subsp: "",
      f: "",
      species: "vera",
      authors: "(L.) Burm.f.",
      family: "Asphodelaceae",
      var: "",
      subfamily: "",
      sy: ["Aloe barbadensis Mill."],
      vul: ["Sábila (Cuba)", "Aloe Vera (Estados Unidos)"],
      hab: "Planta suculenta que crece en climas cálidos y secos.",
      des: "Planta perenne con hojas carnosas y espinosas, de color verde...",
      cmp: "Contiene vitaminas, minerales, enzimas y aminoácidos.",
      use: "Gel de las hojas.",
      pro: "Cicatrizante, antiinflamatorio, hidratante.",
      app: "Se utiliza para tratar quemaduras, heridas y problemas de la piel.",
      cul: "Se cultiva en regiones cálidas y secas.",
      bib: [
        "Grindlay, D. and Reynolds, T.: The Aloe vera phenomenon: A review of the properties and modern uses of the leaf parenchyma gel, Journal of Ethnopharmacology, 1986.",
      ],
    },
    {
      id: 4,
      name: "Manzanilla",
      genus: "Matricaria",
      subsp: "",
      f: "",
      species: "chamomilla",
      authors: "L.",
      family: "Asteraceae",
      var: "",
      subfamily: "",
      sy: ["Chamomilla recutita (L.) Rauschert"],
      vul: ["Manzanilla (Cuba)", "Camomila (España)"],
      hab: "Hierba anual que crece en campos y bordes de caminos.",
      des: "Planta de unos 20-50 cm de altura, con flores blancas y amarillas...",
      cmp: "Contiene aceites esenciales, flavonoides y cumarinas.",
      use: "Flores.",
      pro: "Antiinflamatorio, digestivo, sedante.",
      app: "Se utiliza para tratar problemas digestivos y como calmante.",
      cul: "Se cultiva en climas templados.",
      bib: ["Blumenthal, M.: The Complete German Commission E Monographs, 1998."],
    },
    {
      id: 5,
      name: "Lavanda",
      genus: "Lavandula",
      subsp: "",
      f: "",
      species: "angustifolia",
      authors: "Mill.",
      family: "Lamiaceae",
      var: "",
      subfamily: "",
      sy: ["Lavandula officinalis Chaix"],
      vul: ["Lavanda (Cuba)", "Lavande (Francia)"],
      hab: "Arbusto perenne que crece en zonas soleadas y secas.",
      des: "Planta de unos 30-60 cm de altura, con flores violetas...",
      cmp: "Contiene aceites esenciales, taninos y cumarinas.",
      use: "Flores y aceite esencial.",
      pro: "Relajante, antiséptico, antiinflamatorio.",
      app: "Se utiliza para tratar ansiedad, insomnio y heridas.",
      cul: "Se cultiva en climas mediterráneos.",
      bib: ["Wichtl, M.: Herbal Drugs and Phytopharmaceuticals, 2004."],
    },
    {
      id: 6,
      name: "Menta",
      genus: "Mentha",
      subsp: "",
      f: "",
      species: "piperita",
      authors: "L.",
      family: "Lamiaceae",
      var: "",
      subfamily: "",
      sy: ["Mentha balsamea Willd."],
      vul: ["Menta (Cuba)", "Peppermint (Inglaterra)"],
      hab: "Hierba perenne que crece en zonas húmedas.",
      des: "Planta de unos 30-90 cm de altura, con hojas verdes y flores lilas...",
      cmp: "Contiene mentol, flavonoides y ácidos fenólicos.",
      use: "Hojas y aceite esencial.",
      pro: "Digestivo, antiespasmódico, carminativo.",
      app: "Se utiliza para tratar problemas digestivos y respiratorios.",
      cul: "Se cultiva en climas templados.",
      bib: ["Grieve, M.: A Modern Herbal, 1931."],
    },
  ];
  